name: $(version)

variables:
  version.major: 0
  version.minor: 3
  patch: $[counter(format('{0}.{1}-{2}', variables['version.major'], variables['version.minor'], variables['Build.SourceBranch']), 0)]
  ${{if eq(variables['Build.Reason'], 'PullRequest')}}:
    version: $[format('pr-{0}.{1}', variables['System.PullRequest.PullRequestNumber'], variables['patch'])]
  ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))}}:
    version: $[format('{0}.{1}.{2}', variables['version.major'], variables['version.minor'], variables['patch'])]
  

trigger:
  batch: true
  branches:
    include:
      - 'master'
pr:
  autoCancel: false
  branches:
    include:
      - 'master'

stages:
  - stage:
    jobs:  
    - job: Build
      steps:
      - checkout: none
      - script: echo Hello, world $(Build.SourceBranch)!!
    - job: Push
      dependsOn: Build
      steps:
      - checkout: none
      - script: echo Hello, world $(Build.SourceBranch)!!