name: $(version)$(sufix)

variables:
  major: 0
  minor: 0
  patch: $[counter(format('{0}.{1}-{2}', variables['major'], variables['minor'], variables['Build.SourceBranch']), 0)]
  version: $[format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])]
  ${{if eq(variables['Build.Reason'], 'PullRequest')}}:
    sufix: $[format('-pr{0}', variables['System.PullRequest.PullRequestNumber'])]
  ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))}}:
    sufix: ''
  

trigger:
  batch: true
  branches:
    include:
      - 'master'
pr:
  autoCancel: false
  branches:
    include:
      - 'master'

stages:
  - stage:
    displayName: Build
    jobs:  
    - job:
      displayName: Build
      steps:
      - checkout: none
      - script: echo Hello, world $(Build.SourceBranch)!!