variables:
  major: 0
  minor: 0
  patch: 0
  sufix: ''

trigger:
  batch: true
  branches:
    include:
      - 'master'
pr:
  autoCancel: false
  branches:
    include:
      - 'master'

stages:
  - stage:
    displayName: PatchVersion
    jobs:
      - job:
        displayName: Compute Version
        pool:
          vmImage: ubuntu-latest
          demands:
            - java
        steps:
          - task: Bash@3
            displayName: 'Set patch'
            condition: eq(variables['Build.SourceBranchName'], 'master')
            inputs:
              targetType: 'inline'
              script: echo "##vso[Task.SetVariable variable=patch]$[counter(variables['Build.SourceBranchName'])]"
          - task: Bash@3
            displayName: 'Set sufix'
            condition: ne(variables['Build.SourceBranchName'], 'master')
            inputs:
              targetType: 'inline'
              script: echo "##vso[Task.SetVariable variable=sufix]-rc"

          - task: Bash@3
            displayName: 'Set build number'
            inputs:
              targetType: 'inline'
              script: echo "##vso[Build.UpdateBuildNumber]$(major).$(minor).$(patch)$(rev:.r)$(sufix)"
  - stage:
    displayName: Build
    jobs:  
    - job:
      displayName: Build
      steps:
      - script: echo Hello, world 2!