name: $(major).$(minor).$(patch)

variables:
  major: 0
  minor: 0
  ${{if eq(variables['Build.Reason'], 'PullRequest')}}:
    patch: $[format('{0}-rc', counter(format('{0}.{1}-{2}', variables['major'], variables['minor'], variables['Build.Reason']), 100))]
  ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'master'))}}:
    patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 1)]
  
trigger:
  batch: true
  branches:
    include:
      - 'master'
pr:
  autoCancel: false
  branches:
    include:
      - 'master'

stages:
  - stage:
    displayName: Build
    jobs:  
    - job:
      displayName: Build
      steps:
      - script: echo Hello, world 3!