variables:
  major: 0
  minor: 0
  ${{if eq(variables['Build.Reason'], 'PullRequest')}}:
    sufix: -rc
  version: $[format('{0}.{1}.{2}{3}', variables['major'], variables['minor'], variables['patch'], variables['sufix'])]
  patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']))]
  

trigger:
  batch: true
  branches:
    include:
      - 'master'
pr:
  autoCancel: false
  branches:
    include:
      - 'master'

stages:
  - stage:
    displayName: PatchVersion
    jobs:
      - job:
        displayName: Compute Version
        pool:
          vmImage: ubuntu-latest
          demands:
            - java
        steps:
          - task: Bash@3
            displayName: 'Set patch'
            condition: eq(variables['Build.SourceBranchName'], 'master')
            inputs:
              targetType: 'inline'
              script: echo "##vso[Task.SetVariable variable=version]$[format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])]"

          - task: Bash@3
            displayName: 'Set build number'
            inputs:
              targetType: 'inline'
              script: echo "##vso[Build.UpdateBuildNumber]$(version)"
  - stage:
    displayName: Build
    jobs:  
    - job:
      displayName: Build
      steps:
      - script: echo Hello, world 2!