name: $(version)

variables:
  major: 0
  minor: 0
  patch: $[counter(format('{0}.{1}-{2}', variables['major'], variables['minor'], variables['Build.SourceBranchName']), 1)]
  ${{if eq(variables['Build.Reason'], 'PullRequest')}}:
    version: $[format('pr-{0}.{1}', variables['System.PullRequest.PullRequestNumber'], variables['patch'])]
  ${{if ne(variables['Build.Reason'], 'PullRequest')}}:
    version: $[format('v{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])]
  
trigger:
  batch: true
  branches:
    include:
      - 'master'
pr:
  autoCancel: false
  branches:
    include:
      - 'master'

stages:
  - stage:
    displayName: Build
    jobs:  
    - job:
      displayName: Build
      steps:
      - script: echo Hello, world 4!