${{if eq(variables['Build.Reason'], 'PullRequest')}}:
name: pr-$(System.PullRequest.PullRequestNumber).$(patch)
${{if ne(variables['Build.Reason'], 'PullRequest')}}:
name: $(major).$(minor).$(patch)

variables:
  major: 0
  minor: 0
  patch: $[counter(format('{0}.{1}-{2}', variables['major'], variables['minor'], variables['Build.SourceBranchName']), 1)]  
  
trigger:
  batch: true
  branches:
    include:
      - 'master'
pr:
  autoCancel: false
  branches:
    include:
      - 'master'

stages:
  - stage:
    displayName: Build
    jobs:  
    - job:
      displayName: Build
      steps:
      - script: echo Hello, world 4!