name: $(major).$(minor).$(patch)

variables:
  major: 0
  minor: 0
  ${{if eq(variables['Build.Reason'], 'PullRequest')}}:
    patch: '0-rc'
  ${{if ne(variables['Build.Reason'], 'PullRequest')}}:
    patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']))]
  
trigger:
  batch: true
  branches:
    include:
      - 'master'
pr:
  autoCancel: false
  branches:
    include:
      - 'master'

stages:
  - stage:
    displayName: PatchVersion
    jobs:
      - job:
        displayName: Compute Version
        pool:
          vmImage: ubuntu-latest
          demands:
            - java
        steps:
          - task: Bash@3
            condition: eq(variables['Build.SourceBranchName'], 'master')
            displayName: 'Set build number'
            inputs:
              targetType: 'inline'
              script: |
                echo "##vso[Task.SetVariable variable=path]$(version)"
                echo "##vso[Build.UpdateBuildNumber]$(version)"
  - stage:
    displayName: Build
    jobs:  
    - job:
      displayName: Build
      steps:
      - script: echo Hello, world 2!